### ISSUE TITLE
Problem List items should not be filtered based on encounter

### ISSUE THREAD

**Issue by nbashyam** [drajer-health/eCRNow#164]
Only active problems should be concerned which means abatement date is absent.

**Comment by ElizHough** [comment]
Encounter-diagnosis is included as a FHIR condition, with a category of encounter-diagnosis. These conditions can not be excluded based on abatement date.

**Comment by nbashyam** [comment]
Already committed as part of other PRs on 2/19/2021

**Comment by Torin-Shepard-athena** [comment]
Some clinics enter positive COVID diagnosis with Condition.onset = abatement.

I think the comments by @nbashyam are not correct.  I believe Condition.category encounter-diagnosis is currently considered only if abatement is null .If abatement is not null, the current implementation will always exclude and filter out the Condition resource from the match triggering decision.

@ElizHough FYI

I believe enhancements are required to have logic that will use non-null Condition.abatement values and include them in match triggering decision given the appropriate business logic and checks.

/eCRNow/src/main/java/com/drajer/sof/utils/R4ResourcesData.java getConditionData method

Change FROM existing logic:
``` java
  if (condition.getAbatement() == null && condition.hasCategory()) {
    // consider for inclusion in triggering decision only if Condition does not have stop date
    // this block checks if Condition.category is encounter-diagnosis
  } else {
    conditionMissingAbatement++;
  }
```

The else block should be enhanced to consider stop date value and add it for inclusion in triggering decision if it has same date as the encounter.  The actual stop date value must be checked because eICR generation should not be triggered on historic problems entered with a stop date that is in the past.  However, if non-null stop date is the same as the date of the triggering encounter, then it should be included in the match triggering decision.

Suggested Change TO:
``` java
  if (condition.getAbatement() == null) /* remove and expression that checks category; move into if and else blocks */ {
    // Consider for inclusion in triggering decision when Condition does not have abatement
    // check if (condition.hasCategory()) before checking if Condition.category is encounter-diagnosis
  } else {
    // Consider Condition.category and the non-null Condition.abatement value
    if (condition.hasCategory()
        and Condition.category contains encounter-diagnosis
        and Condition.encounter is not null and is the same as launchDetails.encounterid) {
      // Always check if Condition should be used for triggering when category is encounter-diagnosis
      // if abatement is not null, check if the value is contained in the time period for the triggering encounter
      if (Condition.abatement is between Encounter.period.start and end) {
        // Since category is encounter-diagnosis, include check if this Condition is contained in the triggering encounter
        if (condition
            .getEncounter()
            .getReference()
            .equals("Encounter/" + launchDetails.getEncounterId())) {
          then add to triggerable conditionCodes list;
        } else {
          conditionMissingAbatement++;
        }
      } else {
        conditionMissingAbatement++;
      }
    } else if (Condition.abatement is between Encounter.period.start and end) {
      // if abatement is not null and category does not contain encounter-diagnosis, compare abatement to encounter date
      // This will prevent triggering on historic problems entered into the problem list
      then add to triggerable conditionCodes list;
    } else {
      conditionMissingAbatement++;
    }
  }
```
