### ISSUE TITLE
Filter Encounter Diagnosis and Pregnancy Conditions from the problem list

### ISSUE THREAD

**Issue by nbashyam** [drajer-health/eCRNow#178]

**Comment by nbashyam** [comment]
Add Encounter Diagnosis to the Encounter Section

**Comment by nbashyam** [comment]
IF the Encounter Diagnosis is not associated with an Encounter Reference , then the resource will never appear in the Encounter Section or the Problem Section. If the Encounter Diagnosis matches the Encounter passed in, then it will be added into the Encounter Section.

**Comment by ElizHough** [comment]
If Pregnancy condition has abatementDateTime valued, then it should not appear in the Social History section.

**Comment by ElizHough** [comment]
Prior to changes made to support Problems at the person level, the History of Present Illness section only contained the Encounter-Diagnosis (condition at the encounter level). After changes made to Problems section, the History of Present Illness section now contains all conditions without an abatementDateTime, including Pregnancy. The History of Present Illness section describes the history related to the reason for the encounter. Since we currently do not expose the HPI from the chart, we should only be including  Encounter-Diagnosis (conditions at the encounter level). Need to retest the History of Present Illness  section.

**Comment by nbashyam** [comment]
This has been updated and resolved prior to 3/1 baseline
