### ISSUE TITLE
Stopping ECR checks on long running encounters

### ISSUE THREAD

**Issue by mthrilok** [drajer-health/eCRNow#450]
Creating this jira reference to track the email conversation.

We currently suspend ECR check on encounters that are 7 days old. However, we are proposing that we move this down to 3 days for stability and performance concerns.

**Comment by nviator** [comment]
@nbashyam contributing my notes from the context of EHR onboarding conversations: 

o	Short-term: Resolution will require an eRSD change. The App team will work on the eRSD to create the pathway and test automatically cease triggering checks on AMB encounters at 3 days.
	Work slated to initiate on 2/6; ETA for availability to is 2/20/23. 
o	Mid-term: Pursue use of the patient relaunch API

**Comment by sathieshkumar** [comment]
@nbashyam  I have tried the eRSD and observed the below issues:
1. 72 hours logic is not working properly if off hours timer is enabled. The off hours logic moves the task to off hours from current time instead of the intended scheduled time.
2. Add encounter class OBSENC to hospital encounter class list
3. Encounter start date is caled culated with the offset in healthcare_Setting configuration.
4. Introduce new reporting duration param for ambulatory encounters. Create close-encounter/terminate-encounter actions for ambulatory encounter.

**Comment by mthrilok** [comment]
hi @nbashyam  -- As discussed in call today , please review the issues listed above and share the updated changes with us to validate it again. Thanks

**Comment by nbashyam** [comment]
The above issues have been addressed as part of the August 2023 ERSD release version 1.2.0.0
