### ISSUE TITLE
Issue/Question - Dealing with patient merges

### ISSUE THREAD

**Issue by c-at-f** [drajer-health/eCRNow#541]
Is there guidance on how the app is expected to work in patient merge scenarios? We had a merge after the initial trigger and subsequent requests from the app failed due to patient ID being incorrect.

**Comment by medhost-chara** [comment]
Is there any update? We will need to handle encounter/patient merges as well.

**Comment by medhost-chara** [comment]
Scenarios which occur at our facilities and the associated ADT event for reference:
Cancel Encounters A11
Cancel Discharge A13
Merge Patient Information A34 and A35

**Comment by nbashyam** [comment]
The following is the currently recommended solution as each EHR deals with patient merges differently.

1. When a Patient Record P1 is merged with a Patient record P2 the following can be done.
2. A launchPatient request can be created for the new record with a new Id or old Id and it will take care of the needed reporting.
3. If a launch Patient was already called for the same patient and encounter for say P1 , but after the merge the record is now tagged as P2. Then the P1 launchPatient will eventually fail and will be moved out. However if P2 is launched then P2 will be used for reporting, thus preventing any loss of reporting. 
4. If both of them were launched previously then P1 will fail and P2 will continue to succeed. 
5. If you old timers have been removed because of inactivity, then you can do a relaunchPatient.
