### ISSUE TITLE
If the concern act is completed/resolved, the problem entry should not be included in EICR

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#626]
- If the concern act is completed/resolved, the problem entry should not be included
- If the problem observation is completed/resolved, the problem entry should not be included

**Comment by AGABB** [comment]
Hello @lakshman301195 - Generally the desired behavior from PHAs is for Active Problems to be included in the Problem List section of the document. Can you please confirm a few details that will help in looking into this?

1. Have you seen example eICRs where there is a Concern Act with a status of Resolved, but the problem entry is included? If so, could you please share the snippet and relevant resource from LQ, ensuring it has been scraped of any PHI. Email works for sending this please make sure to include twy8@cdc.gov and Dragon. 
2. Regarding inclusion of completed problems in general, can you please clarify the expected behavior vs behavior you are seeing? 
3. More specifically, what is the Condition.ClinicalStatus of the 'completed/resolved' conditions that you are seeing make their way into the eICR?

**Comment by mmatiasalt** [comment]
Hi @lakshman301195, following up to see if you are able to provide the request above? Thank you!

**Comment by lakshman301195** [comment]
Hi @mmatiasalt ,

We will be discussing this with Dragon on 8-Jan-2024 during our weekly syncup.

FYI. This same issue has been reported by the Data Quality Team of KS, UT, WV, MN and several other PHA's.

**Comment by mmatiasalt** [comment]
Hi @lakshman301195, I understand this issue wasn't discussed in today's call. Do you mind please uploading the examples here so that the team can review prior to the next discussion? Thank you.

**Comment by nbashyam** [comment]
Please check the Condition.abatementDate field and see if the clinicalStatus field is in-sync with the dates. Discuss on next call.

**Comment by nbashyam** [comment]
Closed after discussion with Athena. 1/29/2024
