### ISSUE TITLE
Pull and Store Provider Information in a DB Column in ph_messages table

### ISSUE THREAD

**Issue by lakshman301195** [drajer-health/eCRNow#630]
Requirement is to associate EICRs with the rendering provider. During the EICR creation process,  add the provider id to the ph_messages table in a separate column

**Comment by mmatiasalt** [comment]
Hi @lakshman301195 , The team is reviewing your request. Can you please provide more information/examples on what the renderingproviderID is and how it can be obtained? Please provide xml and/or loading queries or screenshots if available. Thank you.

**Comment by mmatiasalt** [comment]
@lakshman301195 are you able to provide   more information/examples on what the renderingproviderID is and how it can be obtained? Please provide xml and/or loading queries or screenshots if available. Thank you.

**Comment by lakshman301195** [comment]
Hi @mmatiasalt ,

Please find the response as below. While calling the encounter FHIR API, we will be able to get this information.


Sample Encounter FHIR JSON: 
[sample-encounter.json](https://github.com/drajer-health/eCRNow/files/13856902/sample-encounter.json)

Sample Provider ID to be pulled from above response: a-xxxx.Provider-1

**Comment by nbashyam** [comment]
we cannot add the provider to ph_messages since there may be many providers associated with the encounter.
This can be solved by joining the ph_messages with notificaation_context table using notification_id which is a FK in ph_messages table pointing back to the notification_context.
The notification_data column will have the Encounter resource in the Bundle from where you can access the attribute.
