### ISSUE TITLE
Support externally administered immunizations

### ISSUE THREAD

**Issue by kmarx** [drajer-health/eCRNow#777]
Data quality metrics reports from the CDC for our soft go-live practices are calling out a missing `effectiveTime` for immunizations that are documented in the EHR as being administered off-site, where patients may not recall the date of service.

The distinction for this in FHIR is represented by [Immunization.primarySource.](http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-immunization-definitions.html#Immunization.primarySource) 

We'd like to request that ECRNow support the `primarySource` element.
 
The CDC/AIMS ECR onboarding team that we're working with has indicated that they're happy to collaborate as needed to research how this element should be reflected in the eICR CDA data.  I'll share this ticket with them so they can collaborate as needed. (They may need to update their quality metrics tooling for this as well.)

**Comment by nbashyam** [comment]
I dont see a place for this in the eICR, please forward to Sarah for further analysis.

**Comment by mmatiasalt** [comment]
Hi @kmarx , 

We were able to review this with our standards team and the response is as follows: 
There is no data element in C-CDA Immunization Activity to represent the FHIR concept of Immunization.primarySource: boolean (Definition: “An indication that the content of the record is based on information from the person who administered the vaccine. This reflects the context under which the data was originally recorded. Reflects the “reliability” of the content.”). A missing effectiveTime in the C-CDA template cannot reliably be considered to map to Immunization.primarySource. 

Note that, currently, the CDA to FHIR transforms automatically populate this Immunization.primarySource (it’s a required data element) with False and output the following comment: “INFO: Defaulting primarySource to false since this info is not in the C-CDA Immunization Activity template”. However, this is not correct and should be populated with a data absent reason. The transforms will be updated as required. 

Thank you

**Comment by nbashyam** [comment]
Will not be addressed currently due to the deficiency in the standards.
